#!/bin/sh

cd $HOME

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:devhammed/dotfiles.git"

is_not_installed() {
  ! command -v $1 >/dev/null 2>&1
}

if is_not_installed brew; then
  echo "Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

if [ -f "$HOME/.Brewfile" ]; then
  echo "Updating homebrew bundle"
  brew bundle --global
fi

if is_not_installed deno; then
  curl -fsSL https://deno.land/x/install/install.sh | sh
fi

if is_not_installed flutter; then
  echo "Installing flutter"
  flutter_sdk_path="$HOME/.local/share/flutter"
  mkdir -p $flutter_sdk_path
  git clone https://github.com/flutter/flutter.git -b beta $flutter_sdk_path
fi

if is_not_installed rustc; then
  echo "Installing rust"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

if is_not_installed composer; then
  echo "Installing PHP composer"
  local_bin="$HOME/.local/bin"
  mkdir -p $local_bin
  wget -O $local_bin/composer https://getcomposer.org/composer-stable.phar
fi

if is_not_installed zsh; then
  echo "Installing zsh"
  sudo apt install zsh
  echo "Changing current user shell to zsh"
  chsh -s `which zsh` $USER
fi

ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
ZSH_CUSTOM_PLUGINS="$ZSH_CUSTOM/plugins"

if [ ! -d "$ZSH_CUSTOM" ]; then
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [ ! -d "$ZSH_CUSTOM/themes/spaceship-prompt" ]; then
  git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
  ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
fi

if [ ! -d "$ZSH_CUSTOM_PLUGINS/zsh-completions" ]; then
  git clone https://github.com/zsh-users/zsh-completions "$ZSH_CUSTOM_PLUGINS/zsh-completions"
fi

if [ ! -d "$ZSH_CUSTOM_PLUGINS/zsh-syntax-highlighting" ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM_PLUGINS/zsh-syntax-highlighting"
fi

if [ ! -d "$ZSH_CUSTOM_PLUGINS/zsh-autosuggestions" ]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM_PLUGINS/zsh-autosuggestions"
fi
